name: Clang-Tidy

on:
  pull_request:
    branches: [ master, clang-tidy ]
    paths: [ '**.cpp', '**.h' ]

jobs:
  build:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
    - name: Analyze
      run: |
        git diff -U0 HEAD^ | clang-tidy-diff.py -p1 -export-fixes clang-tidy-fixes.yml
