name: Clang-Tidy

on:
  pull_request_target:
    branches: [ master, clang-tidy-secure ]
    paths: [ '**.cpp', '**.h' ]

jobs:
  build:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        persist-credentials: false
    - name: Prepare compile_commands.json
      run: |
        # Generate the compile_commands.json in a naive way, don't use anything that can run scripts supplied by untrusted forks (i.e. CMake)
        {
            echo "["
            find src -name "*.cpp" -type f -exec echo "{ \"directory\": \"$GITHUB_WORKSPACE/\", \"file\": \"$GITHUB_WORKSPACE/{}\" }," \;
        } > compile_commands.json
        # Strip the last comma
        sed -i "\$ s/,\$//" compile_commands.json
        echo "]" >> compile_commands.json
    - name: Analyze
      uses: ZedThree/clang-tidy-review@v0.7.0
      with:
        apt_packages: libsdl2-dev,libsdl2-image-dev,libsdl2-mixer-dev,libsdl2-ttf-dev
        clang_tidy_checks:
