name: Clang-Tidy

on:
  pull_request:
    branches: [ test-base ]
    paths: [ '**.cpp', '**.h' ]

jobs:
  tidy:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Analyze
      run: |
        git diff -U0 HEAD^
