name: MSVC

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        config:
        - name: SDL2 x86
          platform: x86
          build_config: Release-SDL2
          deploy_config: SDL2
          package_name: fheroes2_windows_x86_SDL2
          release_name: Windows x86 build with SDL2 support (latest commit)
          release_tag: fheroes2-windows-x86-SDL2
    name: MSVC (${{ matrix.config.name }})
    runs-on: windows-2019
    timeout-minutes: 120
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Prepare VCPKG cache
      uses: actions/cache@v3
      with:
        path: ~/AppData/Local/vcpkg/archives
        key: msvc-vcpkg-cache-${{ github.sha }}
        restore-keys: |
          msvc-vcpkg-cache-
    - name: Install dependencies, cygwin and zip
      run: |
        script/windows/setup_vcpkg.bat C:/vcpkg ${{ matrix.config.platform }} VisualStudio/packages/installed
        ls -lR C:/vcpkg/packages
