name: Push

on:
  push:
    branches: [ test ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  translation:
    name: Translation update
    uses: ./.github/workflows/translation_update.yml
